CREATE TABLE filial
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(100) NOT NULL,
    endereco VARCHAR(200) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    sigla_estado VARCHAR(2) NOT NULL,
    numero_coluna INT NOT NULL,
    numero_linha INT NOT NULL,
    capacidade_maxima INT NOT NULL,
    CONSTRAINT filial_pkey PRIMARY KEY (id) -- Adicionado
);

CREATE TABLE usuario
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(150) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    cargo_usuario VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT true,
    filial_id BIGINT,
    CONSTRAINT usuario_pkey PRIMARY KEY (id), -- Adicionado
    FOREIGN KEY (filial_id) REFERENCES filial(id)
);

CREATE TABLE moto
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa VARCHAR(7) NOT NULL UNIQUE,
    chassi VARCHAR(17) NOT NULL UNIQUE,
    modelo_moto VARCHAR(50) NOT NULL,
    ano INT NOT NULL,
    status_moto VARCHAR(50) NOT NULL,
    filial_id BIGINT NOT NULL,
    CONSTRAINT moto_pkey PRIMARY KEY (id),
    FOREIGN KEY (filial_id) REFERENCES filial(id)
);

CREATE TABLE posicao_patio
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    identificacao VARCHAR(255) NOT NULL,
    numero_linha INT NOT NULL,
    numero_coluna INT NOT NULL,
    area VARCHAR(50) NOT NULL,
    ocupado BOOLEAN NOT NULL,
    moto_id BIGINT,
    filial_id BIGINT NOT NULL,
    CONSTRAINT posicao_patio_pkey PRIMARY KEY (id),
    CONSTRAINT fk_posicao_patio_filial FOREIGN KEY (filial_id) REFERENCES filial(id),
    CONSTRAINT uk_posicao_patio_moto_id UNIQUE (moto_id),
    CONSTRAINT fk_posicao_patio_moto FOREIGN KEY (moto_id) REFERENCES moto(id)
);

CREATE TABLE problema
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_problema VARCHAR(50) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_registro DATE NOT NULL,
    resolvido BOOLEAN NOT NULL,
    moto_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT problema_pkey PRIMARY KEY (id), -- Adicionado
    FOREIGN KEY (moto_id) REFERENCES moto(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);